//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMIU.WRMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AT_ExpenseSanction
    {
        public long ID { get; set; }
        public Nullable<long> MonthlyExpenseID { get; set; }
        public Nullable<long> SanctionID { get; set; }
        public string Status { get; set; }
        public string VendorType { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual AT_MonthlyExpenses AT_MonthlyExpenses { get; set; }
        public virtual AT_Sanction AT_Sanction { get; set; }
    }
}
