//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMIU.WRMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_ComplaintType
    {
        public CM_ComplaintType()
        {
            this.CM_Complaint = new HashSet<CM_Complaint>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public Nullable<short> ResponseTime { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual ICollection<CM_Complaint> CM_Complaint { get; set; }
    }
}
