//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMIU.WRMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_ChannelReachHistory
    {
        public long ID { get; set; }
        public Nullable<long> ReachID { get; set; }
        public int FromRD { get; set; }
        public int ToRD { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual CO_ChannelReach CO_ChannelReach { get; set; }
    }
}
