//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMIU.WRMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_ChannelReach
    {
        public CO_ChannelReach()
        {
            this.CO_ChannelReachHistory = new HashSet<CO_ChannelReachHistory>();
            this.CO_ChannelReachLSP = new HashSet<CO_ChannelReachLSP>();
        }
    
        public long ID { get; set; }
        public Nullable<long> ChannelID { get; set; }
        public int FromRD { get; set; }
        public int ToRD { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual ICollection<CO_ChannelReachHistory> CO_ChannelReachHistory { get; set; }
        public virtual ICollection<CO_ChannelReachLSP> CO_ChannelReachLSP { get; set; }
        public virtual CO_Channel CO_Channel { get; set; }
    }
}
