//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMIU.WRMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_PoliceStation
    {
        public CO_PoliceStation()
        {
            this.CO_ChannelAdminBoundries = new HashSet<CO_ChannelAdminBoundries>();
            this.CO_Village = new HashSet<CO_Village>();
            this.FO_StructureAdminBoundaries = new HashSet<FO_StructureAdminBoundaries>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<long> TehsilID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<long> OldID { get; set; }
    
        public virtual ICollection<CO_ChannelAdminBoundries> CO_ChannelAdminBoundries { get; set; }
        public virtual ICollection<CO_Village> CO_Village { get; set; }
        public virtual ICollection<FO_StructureAdminBoundaries> FO_StructureAdminBoundaries { get; set; }
    }
}
