//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMIU.WRMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EC_GenerateBillParameters
    {
        public EC_GenerateBillParameters()
        {
            this.EC_Bills = new HashSet<EC_Bills>();
        }
    
        public long ID { get; set; }
        public string ServiceType { get; set; }
        public string FinancialYear { get; set; }
        public Nullable<System.DateTime> BillIssueDate { get; set; }
        public Nullable<System.DateTime> BillDueDate { get; set; }
        public Nullable<bool> IncludApplicableTaxes { get; set; }
        public string AdjustmentAddSub { get; set; }
        public string AdjustmentType { get; set; }
        public Nullable<double> AdjustmentAmount { get; set; }
        public string AdjustmentReason { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual ICollection<EC_Bills> EC_Bills { get; set; }
    }
}
