//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMIU.WRMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FO_FFPArrangements
    {
        public long ID { get; set; }
        public long FFPID { get; set; }
        public short FFPArrangementTypeID { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual FO_FFPArrangementType FO_FFPArrangementType { get; set; }
        public virtual FO_FloodFightingPlan FO_FloodFightingPlan { get; set; }
    }
}
