//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMIU.WRMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FO_Items
    {
        public FO_Items()
        {
            this.FO_PreMBStatus = new HashSet<FO_PreMBStatus>();
            this.FO_EPItem = new HashSet<FO_EPItem>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public short ItemCategoryID { get; set; }
        public string MajorMinor { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual FO_ItemCategory FO_ItemCategory { get; set; }
        public virtual ICollection<FO_PreMBStatus> FO_PreMBStatus { get; set; }
        public virtual ICollection<FO_EPItem> FO_EPItem { get; set; }
    }
}
