//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMIU.WRMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IF_IrrigatorFeedback
    {
        public long ID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<long> IrrigatorID { get; set; }
        public string Remarks { get; set; }
        public string TailStatus { get; set; }
        public string RotaionalViolation { get; set; }
        public string WaterTheft { get; set; }
        public Nullable<System.DateTime> FeedbackDate { get; set; }
        public Nullable<int> RD { get; set; }
        public string LocalName { get; set; }
        public Nullable<long> VillageID { get; set; }
    
        public virtual CO_Village CO_Village { get; set; }
        public virtual IF_Irrigator IF_Irrigator { get; set; }
    }
}
