//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMIU.WRMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IW_PunjabIndent
    {
        public long ID { get; set; }
        public System.DateTime FromIndentDate { get; set; }
        public System.DateTime ToIndentDate { get; set; }
        public Nullable<double> Thal { get; set; }
        public Nullable<double> CJ { get; set; }
        public Nullable<double> GTC { get; set; }
        public Nullable<double> ChashmaDS { get; set; }
        public Nullable<double> CRBCPunjab { get; set; }
        public Nullable<double> Mangla { get; set; }
        public string Remarks { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
