//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMIU.WRMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RP_Channel
    {
        public long ID { get; set; }
        public long RPID { get; set; }
        public Nullable<long> GroupID { get; set; }
        public Nullable<long> SubGroupID { get; set; }
        public long ChannelID { get; set; }
        public double Discharge { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual RP_RotationalProgram RP_RotationalProgram { get; set; }
        public virtual CO_Channel CO_Channel { get; set; }
    }
}
