//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMIU.WRMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UA_ActingRoles
    {
        public long ID { get; set; }
        public long UserID { get; set; }
        public Nullable<long> AssignedUserID { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<long> DesignationID { get; set; }
        public Nullable<long> AssignedDesignationID { get; set; }
    
        public virtual UA_Designations UA_Designations { get; set; }
        public virtual UA_Designations UA_Designations1 { get; set; }
        public virtual UA_Users UA_Users { get; set; }
        public virtual UA_Users UA_Users1 { get; set; }
    }
}
