//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMIU.WRMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UA_AndroidScreens
    {
        public UA_AndroidScreens()
        {
            this.UA_AndroidRoleRights = new HashSet<UA_AndroidRoleRights>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<long> ParentID { get; set; }
        public Nullable<long> ModuleID { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<bool> ShowInMenu { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual ICollection<UA_AndroidRoleRights> UA_AndroidRoleRights { get; set; }
        public virtual UA_Modules UA_Modules { get; set; }
    }
}
