//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMIU.WRMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WL_ReachLagHistory
    {
        public long ID { get; set; }
        public long ReachLagID { get; set; }
        public Nullable<long> ChannelComndTypeID { get; set; }
        public Nullable<long> FromStructureTypeID { get; set; }
        public Nullable<long> FromStationID { get; set; }
        public Nullable<long> ToStructureTypeID { get; set; }
        public Nullable<long> ToStationID { get; set; }
        public string Name { get; set; }
        public Nullable<double> Nov_April { get; set; }
        public Nullable<double> May_June { get; set; }
        public Nullable<double> Jul_Aug { get; set; }
        public Nullable<double> Sep_Oct { get; set; }
        public Nullable<short> SortOrder { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual WL_ReachLag WL_ReachLag { get; set; }
    }
}
